import "./globals.css"
import type { Metadata } from "next"
import Link, { type LinkProps } from "next/link"
import type { CSSProperties, FC, PropsWithChildren } from "react"
import clsx from "clsx"
import { Analytics } from "@vercel/analytics/react"
import { Button } from "ui"
import Image from "next/image"
import Script from "next/script"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

const NavbarLink: FC<PropsWithChildren<LinkProps>> = ({ children, ...props }) => {
  return (
    <Button asChild size="navbar" variant="navbar" weight="semi-bold">
      <Link {...props}>{children}</Link>
    </Button>
  )
}

export default function RootLayout({ children }: PropsWithChildren): JSX.Element {
  // const getTodos = async () => {
  //   const response = await fetch("http://localhost:3000/api/todos/get")
  //   const todos = await response.json()
  //   console.log(todos)
  // }
  // getTodos()

  return (
    <html lang="en">
      <head>
        <Script data-domain="yann-lauwers.io" defer src="https://plausible.io/js/script.js" />
      </head>
      <body
        className={clsx("bg-background min-h-screen font-sans antialiased")}
        style={{ "--navmargin": "1.5rem", "--navheight": "2.5rem" } as CSSProperties}
      >
        <main className="h-full">
          <div className="fixed inset-x-0 top-0 mx-auto max-w-5xl  pt-[var(--navmargin)]">
            <div className="flex h-[var(--navheight)] items-center gap-4 p-4">
              <Button asChild className="hidden flex-1 sm:block" unstyled>
                <Link href="/">
                  <Image
                    alt=""
                    className="aspect-square h-10 w-10 rounded-full"
                    height={48}
                    src="https://picsum.photos/64/64"
                    width={48}
                  />
                </Link>
              </Button>
              <div className="flex-1">
                <div className="mx-auto flex w-max rounded-3xl bg-white px-2 shadow-sm">
                  <NavbarLink href="/about">About</NavbarLink>
                  <NavbarLink href="/career">Career</NavbarLink>
                  <NavbarLink href="/projects">Projects</NavbarLink>
                  <NavbarLink href="/uses">Uses</NavbarLink>
                </div>
              </div>
              <div className="invisible hidden flex-1 sm:block" />
            </div>
          </div>
          <div className="flex h-full items-center justify-center py-[calc(var(--navmargin)_+_var(--navheight))]">
            <p>This website is under construction</p>
          </div>
          <div className="hidden">{children}</div>
          <Analytics />
        </main>
      </body>
    </html>
  )
}
